# Generated by Django 2.1.15 on 2022-02-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='odontograma',
            fields=[
                ('idOdontograma', models.AutoField(primary_key=True, serialize=False)),
                ('P18', models.CharField(max_length=50)),
                ('P17', models.CharField(max_length=50)),
                ('P16', models.CharField(max_length=50)),
                ('P15', models.CharField(max_length=50)),
                ('P14', models.CharField(max_length=50)),
                ('P13', models.CharField(max_length=50)),
                ('P12', models.CharField(max_length=50)),
                ('P11', models.CharField(max_length=50)),
                ('P55', models.CharField(max_length=50)),
                ('P54', models.CharField(max_length=50)),
                ('P53', models.CharField(max_length=50)),
                ('P52', models.CharField(max_length=50)),
                ('P51', models.CharField(max_length=50)),
                ('P21', models.CharField(max_length=50)),
                ('P22', models.CharField(max_length=50)),
                ('P23', models.CharField(max_length=50)),
                ('P24', models.CharField(max_length=50)),
                ('P25', models.CharField(max_length=50)),
                ('P26', models.CharField(max_length=50)),
                ('P27', models.CharField(max_length=50)),
                ('P28', models.CharField(max_length=50)),
                ('P61', models.CharField(max_length=50)),
                ('P62', models.CharField(max_length=50)),
                ('P63', models.CharField(max_length=50)),
                ('P64', models.CharField(max_length=50)),
                ('P65', models.CharField(max_length=50)),
                ('P85', models.CharField(max_length=50)),
                ('P84', models.CharField(max_length=50)),
                ('P83', models.CharField(max_length=50)),
                ('P82', models.CharField(max_length=50)),
                ('P81', models.CharField(max_length=50)),
                ('P48', models.CharField(max_length=50)),
                ('P47', models.CharField(max_length=50)),
                ('P46', models.CharField(max_length=50)),
                ('P45', models.CharField(max_length=50)),
                ('P44', models.CharField(max_length=50)),
                ('P43', models.CharField(max_length=50)),
                ('P42', models.CharField(max_length=50)),
                ('P41', models.CharField(max_length=50)),
                ('P71', models.CharField(max_length=50)),
                ('P72', models.CharField(max_length=50)),
                ('P73', models.CharField(max_length=50)),
                ('P74', models.CharField(max_length=50)),
                ('P75', models.CharField(max_length=50)),
                ('P31', models.CharField(max_length=50)),
                ('P32', models.CharField(max_length=50)),
                ('P33', models.CharField(max_length=50)),
                ('P34', models.CharField(max_length=50)),
                ('P35', models.CharField(max_length=50)),
                ('P36', models.CharField(max_length=50)),
                ('P37', models.CharField(max_length=50)),
                ('P38', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='historial',
            name='correo',
        ),
        migrations.AddField(
            model_name='historial',
            name='antecedentesPersonales',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='idPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente'),
        ),
        migrations.AddField(
            model_name='historial',
            name='idTratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.tratamiento'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tipoSangre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='idOdontograma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.odontograma'),
        ),
    ]
