# Generated by Django 2.1.15 on 2022-02-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_auto_20220207_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=250)),
                ('especialidad', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='idDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.doctor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente'),
        ),
    ]
