# Generated by Django 2.1.15 on 2022-02-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_auto_20220208_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=10, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=250, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecNacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
