# Generated by Django 2.1.15 on 2022-02-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_auto_20220208_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=200),
        ),
    ]
