# Generated by Django 2.1.15 on 2022-02-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='alergia',
            fields=[
                ('idAlergia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='historial',
            name='alergiaMedicamento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='antecedentePersonal',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='descripcionAlergia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='descripcionMedicamento',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='descripcionTrastorno',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='descripcionTratamientoOrtodoncia',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='medicamento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='motivoConsulta',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='peso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='signoPrincipal',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='tiempoEnfermedad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='trastornoNervioso',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='tratamientoOrtodoncia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='idAlergia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.alergia'),
        ),
    ]
