# Generated by Django 2.1.15 on 2022-02-25 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0010_ingresousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='tipoSangre',
            new_name='frecuenciaCardiaca',
        ),
        migrations.AddField(
            model_name='historial',
            name='frecuenciaRespiratoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='idDoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.doctor'),
        ),
        migrations.AddField(
            model_name='historial',
            name='imc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='presionArterial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='pulso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='respiracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='talla',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='temperatura',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
