# Generated by Django 2.1.15 on 2022-02-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0011_auto_20220224_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='tratamientoRealizado',
            fields=[
                ('idTratamientoRealizado', models.AutoField(primary_key=True, serialize=False)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
                ('idTratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.tratamiento')),
            ],
        ),
    ]
