# Generated by Django 2.1.15 on 2022-02-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0012_tratamientorealizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idTratamiento',
        ),
        migrations.AddField(
            model_name='historial',
            name='idTratamientoRealizado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.tratamientoRealizado'),
        ),
    ]
