# Generated by Django 2.1.15 on 2022-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0014_auto_20220225_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientorealizado',
            name='conclusion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
