# Generated by Django 2.1.15 on 2022-02-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0015_tratamientorealizado_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='descripcionTratamiento',
        ),
    ]
