# Generated by Django 2.1.15 on 2022-02-26 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0017_consulta_idcita'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoCuenta',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('abono', models.FloatField(null=True)),
                ('saldo', models.FloatField(null=True)),
                ('idConsulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.consulta')),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente')),
            ],
        ),
    ]
