# Generated by Django 2.1.15 on 2022-02-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0018_estadocuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocuenta',
            name='idConsulta',
        ),
    ]
