# Generated by Django 2.1.15 on 2022-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0019_remove_estadocuenta_idconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
