# Generated by Django 2.1.15 on 2022-03-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0020_estadocuenta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientotemporal',
            name='resumen',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
