# Generated by Django 2.1 on 2022-03-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0021_tratamientotemporal_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idTratamientoRealizado',
        ),
        migrations.AddField(
            model_name='tratamientorealizado',
            name='diagnostico',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tratamientorealizado',
            name='observacionDiagnostico',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tratamientotemporal',
            name='diagnostico',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tratamientotemporal',
            name='observacionDiagnostico',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
