# Generated by Django 2.1 on 2022-03-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0022_auto_20220306_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='idDoctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Principal.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial',
            name='idPaciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Principal.paciente'),
            preserve_default=False,
        ),
    ]
