# Generated by Django 2.1 on 2022-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0023_auto_20220306_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontograma',
            name='P11',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P12',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P13',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P14',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P15',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P16',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P17',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P18',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P21',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P22',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P23',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P24',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P25',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P26',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P27',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P28',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P31',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P32',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P33',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P34',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P35',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P36',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P37',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P38',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P41',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P42',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P43',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P44',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P45',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P46',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P47',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P48',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P51',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P52',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P53',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P54',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P55',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P61',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P62',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P63',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P64',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P65',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P71',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P72',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P73',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P74',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P75',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P81',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P82',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P83',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P84',
        ),
        migrations.RemoveField(
            model_name='odontograma',
            name='P85',
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP41',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP42',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP43',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP44',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP45',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP46',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP47',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP48',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP51',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP52',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP53',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP54',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP55',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP61',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP62',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP63',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP64',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP65',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP71',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP72',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP73',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP74',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP75',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP81',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP82',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP83',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP84',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='BP85',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP41',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP42',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP43',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP44',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP45',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP46',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP47',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP48',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP51',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP52',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP53',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP54',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP55',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP61',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP62',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP63',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP64',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP65',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP71',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP72',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP73',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP74',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP75',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP81',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP82',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP83',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP84',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='CP85',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP41',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP42',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP43',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP44',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP45',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP46',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP47',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP48',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP51',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP52',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP53',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP54',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP55',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP61',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP63',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP64',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP65',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP71',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP72',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP73',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP74',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP75',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP81',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP82',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP83',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP84',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='LP85',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP41',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP42',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP43',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP44',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP45',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP46',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP47',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP48',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP51',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP52',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP53',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP54',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP55',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP61',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP62',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP63',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP64',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP65',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP71',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP72',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP73',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP74',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP75',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP81',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP82',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP83',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP84',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='RP85',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP34',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP35',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP36',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP37',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP38',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP41',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP42',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP43',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP44',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP45',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP46',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP47',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP48',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP51',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP52',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP53',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP54',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP55',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP61',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP62',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP63',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP64',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP65',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP71',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP72',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP73',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP74',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP75',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP81',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP82',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP83',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP84',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='odontograma',
            name='TP85',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
