# Generated by Django 2.1 on 2022-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0024_auto_20220421_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='LP62',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
