# Generated by Django 2.1 on 2022-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0025_odontograma_lp62'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
