# Generated by Django 2.1 on 2022-05-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0026_odontograma_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
