# Generated by Django 2.1 on 2022-05-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0027_odontograma_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
