# Generated by Django 2.1 on 2022-05-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0028_historial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='frecuenciaCardiaca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuenciaRespiratoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='presionArterial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pulso',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='respiracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
