# Generated by Django 2.1 on 2022-05-30 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0030_auto_20220529_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idAlergia',
        ),
        migrations.AddField(
            model_name='alergia',
            name='idHistorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.historial'),
        ),
    ]
