# Generated by Django 2.1 on 2022-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0031_auto_20220529_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
