# Generated by Django 2.1 on 2022-06-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0035_auto_20220609_0845'),
    ]

    operations = [
        
    ]
