# Generated by Django 2.1 on 2022-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0036_remove_areatratamiento_estado'),
    ]

    operations = [
        
    ]
