# Generated by Django 2.1 on 2022-06-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0037_areatratamiento_estado'),
    ]

    operations = [
        
    ]
