# Generated by Django 2.1 on 2022-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0040_remove_cita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
