# Generated by Django 2.1 on 2022-06-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0041_cita_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='status',
        ),
    ]
