# Generated by Django 2.1 on 2022-06-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0042_remove_cita_status'),
    ]

    operations = [
        
    ]
