# Generated by Django 2.1 on 2022-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0043_auto_20220609_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
