# Generated by Django 2.1 on 2022-06-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0044_auto_20220609_0936'),
    ]

    operations = [
        
    ]
