# Generated by Django 2.1 on 2022-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0045_auto_20220609_1024'),
    ]

    operations = [
        
    ]
