# Generated by Django 2.1 on 2022-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0046_auto_20220609_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
