# Generated by Django 2.1 on 2022-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0048_auto_20220610_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='receta',
            field=models.CharField(max_length=250, null=True),
        )
    ]
