# Generated by Django 2.1.15 on 2022-02-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areaTratamiento',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tratamiento',
            fields=[
                ('idTratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField(max_length=200)),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamiento.areaTratamiento')),
            ],
        ),
    ]
